Repository Arijeet2580/HacktoberfestCode2023, pull requests merged in 2023-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest

#2 Create python_tictactoe.py
  python_tictactoe.py
Labels: good first issue, hacktoberfest

#6 Updated the file organization
  Python/python_tictactoe.py
Labels: documentation, hacktoberfest

#5 Created python_calculator.py
  python_calculator.py
Labels: hactobefest-accepted

#4 Priorty Queue in C
  LinkedLL.c
  PriortyQueue.c
Labels: hactobefest-accepted

#7 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hactobefest-accepted

#10 Added a static Website and a Arduino Project on Gas Leak
  Arduino/Gas_Leak_Alarm/Gas_Leak_Alarm.ino
  HTML_CSS/Website1/assets/asset 0.png
  HTML_CSS/Website1/assets/asset 1.png
  HTML_CSS/Website1/assets/asset 10.svg
  HTML_CSS/Website1/assets/asset 11.svg
  HTML_CSS/Website1/assets/asset 12.svg
  HTML_CSS/Website1/assets/asset 13.svg
  HTML_CSS/Website1/assets/asset 14.svg
  HTML_CSS/Website1/assets/asset 15.svg
  HTML_CSS/Website1/assets/asset 16.svg
  HTML_CSS/Website1/assets/asset 17.svg
  HTML_CSS/Website1/assets/asset 18.png
  HTML_CSS/Website1/assets/asset 19.png
  HTML_CSS/Website1/assets/asset 2.jpeg
  HTML_CSS/Website1/assets/asset 20.png
  HTML_CSS/Website1/assets/asset 21.png
  HTML_CSS/Website1/assets/asset 22.png
  HTML_CSS/Website1/assets/asset 23.png
  HTML_CSS/Website1/assets/asset 24.png
  HTML_CSS/Website1/assets/asset 25.png
  HTML_CSS/Website1/assets/asset 26.png
  HTML_CSS/Website1/assets/asset 27.svg
  HTML_CSS/Website1/assets/asset 28.png
  HTML_CSS/Website1/assets/asset 29.png
  HTML_CSS/Website1/assets/asset 3.png
  HTML_CSS/Website1/assets/asset 30.png
  HTML_CSS/Website1/assets/asset 31.png
  HTML_CSS/Website1/assets/asset 32.png
  HTML_CSS/Website1/assets/asset 33.svg
  HTML_CSS/Website1/assets/asset 34.svg
  HTML_CSS/Website1/assets/asset 35.svg
  HTML_CSS/Website1/assets/asset 36.jpeg
  HTML_CSS/Website1/assets/asset 37.jpeg
  HTML_CSS/Website1/assets/asset 38.jpeg
  HTML_CSS/Website1/assets/asset 39.jpeg
  HTML_CSS/Website1/assets/asset 4.png
  HTML_CSS/Website1/assets/asset 40.png
  HTML_CSS/Website1/assets/asset 41.png
  HTML_CSS/Website1/assets/asset 5.png
  HTML_CSS/Website1/assets/asset 6.png
  HTML_CSS/Website1/assets/asset 7.png
  HTML_CSS/Website1/assets/asset 8.svg
  HTML_CSS/Website1/assets/asset 9.png
  HTML_CSS/Website1/assets/hamburger-menu.svg
  HTML_CSS/Website1/index.html
  HTML_CSS/Website1/large.css
  HTML_CSS/Website1/medium.css
  HTML_CSS/Website1/script.js
  HTML_CSS/Website1/small.css
  HTML_CSS/Website1/style.css
Labels: documentation, enhancement, hacktoberfest, hactobefest-accepted

#15 Create MergeSort.cpp
  DSA/MergeSort.cpp
Labels: enhancement, hacktoberfest, hactobefest-accepted

#16 Sourabh358 patch 3
  C C++/Longest Increasing Subsequence.cpp
  DSA/LongestIncreasingSubsequence.cpp
Labels: enhancement, hacktoberfest, hactobefest-accepted

#17 Updated the readme added an Outro
  README.md
Labels: documentation, good first issue, hacktoberfest, hactobefest-accepted

#22 Added a Java code using oops
  JAVA/interface.java
  JAVA/oops.java
Labels: enhancement, good first issue, hacktoberfest, hactobefest-accepted

#25 quick sort program added
  C C++/quick_sort.cpp
Labels: enhancement, hacktoberfest, hactobefest-accepted

#23 added an static web page game
  TicTacToe/tictactoe.css
  TicTacToe/tictactoe.html
  TicTacToe/tictactoe.js
Labels: enhancement, hacktoberfest, hactobefest-accepted

#27 add Palindrome in Java
  JAVA/Palindrome.java
Labels: enhancement, hacktoberfest, hactobefest-accepted

#30 Added Circular Image Cropper in Python
  Python/Circular Image Cropper/Cropped_Image.png
  Python/Circular Image Cropper/Images/1.jpg
  Python/Circular Image Cropper/Images/10.jpg
  Python/Circular Image Cropper/Images/11.jpg
  Python/Circular Image Cropper/Images/12.jpg
  Python/Circular Image Cropper/Images/2.jpg
  Python/Circular Image Cropper/Images/3.jpg
  Python/Circular Image Cropper/Images/4.jpg
  Python/Circular Image Cropper/Images/5.jpg
  Python/Circular Image Cropper/Images/6.jpg
  Python/Circular Image Cropper/Images/7.jpg
  Python/Circular Image Cropper/Images/8.jpg
  Python/Circular Image Cropper/Images/9.jpg
  Python/Circular Image Cropper/Images/front.jpg
  Python/Circular Image Cropper/README.md
  Python/Circular Image Cropper/circular_image_cropper.py
Labels: enhancement, hacktoberfest, hactobefest-accepted

#29 Bellman Ford AlgoImplement.java
  JAVA/Bellman Ford AlgoImplement.java
Labels: enhancement, hacktoberfest, hactobefest-accepted

#32 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest, hactobefest-accepted
